language: php
php:
  - 5.6
  - 7.0
  - nightly
before_script:
  - composer install
script:
  - composer test
  - composer code-sniffer
after_script:
  - php vendor/bin/coveralls -v
notifications:
  irc:
    channels:
      - "chat.freenode.net#honeybee"
    on_success: always
    on_failure: always
    use_notice: false
    skip_join: false

